from __future__ import annotations

from pathlib import Path

DEFAULT_PROMPT_BUDGET_CHARS = 120_000
CONTEXT_DIRECT_DIFF_MAX_CHARS = 32_000
MAX_TOOL_OUTPUT_CHARS = 12_000
COMMAND_TIMEOUT_SEC = 120
DEFAULT_AGENT_MAX_TURNS = 20
DEFAULT_AGENT_PLANNER_TIMEOUT_SEC = 300
DEFAULT_AGENT_SUMMARY_TIMEOUT_SEC = 45
ALLOWED_FEATURE_ENV_NAME = "authorized_test_env"
ALLOWED_FEATURE_ENV_ID = "authorized_test_env_id"
ALLOWED_FEATURE_ENV_VALUES = (ALLOWED_FEATURE_ENV_NAME, ALLOWED_FEATURE_ENV_ID)

DEFAULT_REPO_ROOTS: tuple[Path, ...] = ()

SECRET_NAMES = (
    "AI_TEST_OFFICER_API_KEY",
    "OPENAI_API_KEY",
    "ARK_API_KEY",
    "VOLCENGINE_API_KEY",
    "TAPD_ACCESS_TOKEN",
    "GONGFENG_ACCESS_TOKEN",
    "TAI_PAT_TOKEN",
    "IWIKI_MCP_TOKEN",
    "WECOM_WEBHOOK_KEY",
    "WECOM_WEBHOOK_URL",
    "WECOM_CALLBACK_TOKEN",
    "WECOM_CALLBACK_ENCODING_AES_KEY",
)
